version: "3.8"
services:
  db01:
    image: choudhurychayan1/vprofiledb:V1
    ports:
      - "3306:3306"
    volumes:
      - vprodbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=vprodbpass
  mc01:
    image: memcached
    ports:
      - "11211:11211"
  rmq01:
    image: rabbitmq
    ports:
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER="guest"
      - RABBITMQ_DEFAULT_PASS="guest"
  vproapp:
    image: choudhurychayan1/vprofile1app:V1
    ports:
      - "8080:8080"
    volumes:
      - vproappdata:/usr/local/tomcat/webapps
  vproweb:
    image: choudhurychayan1/vprofileweb:V1
    ports:
      - "80:80"
        
volumes:
   vprodbdata: {}
   vproappdata: {}